Repository bounswe/bounswe2020group9, pull requests merged in 2020-05, with the labels that each got.

#65 News api
  practice-app/cmpe352API/api_calls.py
  practice-app/cmpe352API/app.py
  practice-app/cmpe352API/hs_err_pid7712.log
  practice-app/cmpe352API/utils.py
Labels: Estimation - Medium, Priority - Urgent, Status - Needs review

#63 Api development covid19
  .DS_Store
  practice-app/.DS_Store
  practice-app/cmpe352API/api_calls.py
  practice-app/cmpe352API/app.py
  practice-app/cmpe352API/covid.py
Labels: Priority - High, Status - Needs review

#72 News unit test
  practice-app/cmpe352API/api_calls.py
  practice-app/cmpe352API/app.py
  practice-app/cmpe352API/test_news.py
  practice-app/cmpe352API/utils.py
Labels: Priority - Urgent, Status - Needs review

#79 Weather API test cases additions
  practice-app/cmpe352API/test_weather.py
Labels: Status - Needs review
